# Shell variables
# Generated by 'wal'
wallpaper='/home/mxnkr/Pictures/wallpaperbetter(18).jpg'

# Special
background='#0d0c0f'
foreground='#bcb5b7'
cursor='#bcb5b7'

# Colors
color0='#0d0c0f'
color1='#6C4A37'
color2='#333748'
color3='#463C48'
color4='#3D4354'
color5='#5F525A'
color6='#91675B'
color7='#bcb5b7'
color8='#837e80'
color9='#6C4A37'
color10='#333748'
color11='#463C48'
color12='#3D4354'
color13='#5F525A'
color14='#91675B'
color15='#bcb5b7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
