--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mxnkr/Pictures/wallpaperbetter(18).jpg"

-- Special
background="#0d0c0f"
foreground="#bcb5b7"
cursor="#bcb5b7"

-- Colors
color0="#0d0c0f"
color1="#6C4A37"
color2="#333748"
color3="#463C48"
color4="#3D4354"
color5="#5F525A"
color6="#91675B"
color7="#bcb5b7"
color8="#837e80"
color9="#6C4A37"
color10="#333748"
color11="#463C48"
color12="#3D4354"
color13="#5F525A"
color14="#91675B"
color15="#bcb5b7"
